// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Week6.SupermercatoEF.Context;

namespace Week6.SupermercatoEF.Migrations
{
    [DbContext(typeof(SupermercatoContext))]
    [Migration("20210624072924_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Dipendente", b =>
                {
                    b.Property<string>("Codice")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength(true);

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataNascita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepartoNumero")
                        .HasColumnType("int");

                    b.HasKey("Codice");

                    b.HasIndex("RepartoNumero");

                    b.ToTable("Dipendente");
                });

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Prodotto", b =>
                {
                    b.Property<string>("Codice")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength(true);

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("decimal");

                    b.Property<int>("RepartoNumero")
                        .HasColumnType("int");

                    b.HasKey("Codice");

                    b.HasIndex("RepartoNumero");

                    b.ToTable("Prodotto");
                });

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Reparto", b =>
                {
                    b.Property<int>("NumeroReparto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NumeroReparto");

                    b.ToTable("Reparto");
                });

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Vendita", b =>
                {
                    b.Property<int>("NumeroVendita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodiceProdotto")
                        .HasColumnType("nchar(5)");

                    b.Property<DateTime>("DataVendita")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantita")
                        .HasColumnType("int");

                    b.HasKey("NumeroVendita");

                    b.HasIndex("CodiceProdotto");

                    b.ToTable("Vendita");
                });

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Dipendente", b =>
                {
                    b.HasOne("Week6.SupermercatoEF.Models.Reparto", "Reparto")
                        .WithMany("Dipendenti")
                        .HasForeignKey("RepartoNumero");

                    b.Navigation("Reparto");
                });

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Prodotto", b =>
                {
                    b.HasOne("Week6.SupermercatoEF.Models.Reparto", "Reparto")
                        .WithMany("Prodotti")
                        .HasForeignKey("RepartoNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reparto");
                });

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Vendita", b =>
                {
                    b.HasOne("Week6.SupermercatoEF.Models.Prodotto", "Prodotto")
                        .WithMany("Vendite")
                        .HasForeignKey("CodiceProdotto");

                    b.Navigation("Prodotto");
                });

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Prodotto", b =>
                {
                    b.Navigation("Vendite");
                });

            modelBuilder.Entity("Week6.SupermercatoEF.Models.Reparto", b =>
                {
                    b.Navigation("Dipendenti");

                    b.Navigation("Prodotti");
                });
#pragma warning restore 612, 618
        }
    }
}
